// Generated by scripts/burger-layers.mjs — do not edit by hand.
export const burgerFrame = { width: 688, height: 1024 };

export const burgerLayers = [
  {
    "name": "bun-top",
    "label": "לחמנייה",
    "src": "/images/burger/bun-top.webp",
    "width": 850,
    "height": 354,
    "left": 19.33,
    "top": 11.04,
    "w": 61.77,
    "restY": 42.73
  },
  {
    "name": "onion",
    "label": "בצל סגול",
    "src": "/images/burger/onion.webp",
    "width": 820,
    "height": 172,
    "left": 20.2,
    "top": 29.59,
    "w": 59.59,
    "restY": 42.84
  },
  {
    "name": "tomato",
    "label": "עגבנייה",
    "src": "/images/burger/tomato.webp",
    "width": 820,
    "height": 190,
    "left": 19.77,
    "top": 37.79,
    "w": 59.59,
    "restY": 20.88
  },
  {
    "name": "lettuce",
    "label": "חסה",
    "src": "/images/burger/lettuce.webp",
    "width": 926,
    "height": 254,
    "left": 16.13,
    "top": 46.88,
    "w": 67.3,
    "restY": -17.8
  },
  {
    "name": "patty",
    "label": "קציצת בקר",
    "src": "/images/burger/patty.webp",
    "width": 858,
    "height": 302,
    "left": 18.31,
    "top": 57.42,
    "w": 62.35,
    "restY": -27.39
  },
  {
    "name": "bun-bottom",
    "label": "לחמנייה קלויה",
    "src": "/images/burger/bun-bottom.webp",
    "width": 834,
    "height": 352,
    "left": 19.19,
    "top": 70.7,
    "w": 60.61,
    "restY": -42.98
  }
] as const;
